export default {
  BLACK: "#000000",
  PRIMARY: "#9f5bff",
  WHITE: "#FFFFFF",
  LIGHT_GRAY: "#EDEDED",
  PRIMARY_LIGHT: "#F1DEFF",
  GRAY: "#7f7f7f",
  CANCELED_RED: "#FF0000",
  CANCELED_RED_LIGHT: "#FFDADA",
  BOOKED_GREEN: "#00FF00",
  BOOKED_GREEN_LIGHT: "#DAFFDA",
  IN_PROGRESS_YELLOW: "#FFFF00",
  IN_PROGRESS_YELLOW_LIGHT: "#FFFFDA",
};
